apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  type: LoadBalancer     # GCP 로드밸런서를 사용하여 외부 IP 할당
  selector:
    app: nginx           # Deployment에서 설정한 라벨과 일치해야 함
  ports:
  - protocol: TCP
    port: 80             # 서비스가 외부로 노출할 포트
    targetPort: 80       # 컨테이너 내부의 포트 (deployment.yaml의 containerPort와 일치)