apiVersion: v1
kind: Service
metadata:
  name: directus-service
spec:
  type: LoadBalancer     # GCP 로드밸런서를 사용하여 외부 IP 할당
  selector:
    app: directus
  ports:
  - protocol: TCP
    port: 8055           # 서비스가 외부로 노출할 포트
    targetPort: 8055     # 컨테이너 내부의 포트 (deployment.yaml의 containerPort와 일치)
